version: "2"

formatters:
  enable:
    - golines
    - gofmt
  settings:
    golines:
      max-len: 100

linters:
  default: none
  enable:
    - errcheck
    - exhaustive
    - gocheckcompilerdirectives
    - godox
    - gomodguard
    - govet
    - iotamixing
    - revive
    - nolintlint
    - testifylint
    - usetesting
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
